/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package aplikasi;

import com.mysql.jdbc.PreparedStatement;
import java.util.HashSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author fikri
 */
public class PaymentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOrderName = new javax.swing.JTextField();
        txtPriceLand = new javax.swing.JTextField();
        cbArea = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbTipeA = new javax.swing.JRadioButton();
        rbTipeB = new javax.swing.JRadioButton();
        rbTipeC = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPriceBuilding = new javax.swing.JTextField();
        txtLargeLand = new javax.swing.JTextField();
        txtLargeBuilding = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbxAgreement = new javax.swing.JCheckBox();
        txtTotalPrice = new javax.swing.JTextField();
        txtInstalmentAmount = new javax.swing.JTextField();
        txtDP = new javax.swing.JTextField();
        txtPPN = new javax.swing.JTextField();
        txtInstalmentMonth = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnProcess = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();

        setTitle("FORM PENJUALAN");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nama Pemesan");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Harga Tanah");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Area");

        txtPriceLand.setEditable(false);
        txtPriceLand.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "SENOPATI", "MENTENG", "KELAPA GADING" }));
        cbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAreaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Harga Bangunan");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tipe Rumah");

        radioButton.add(rbTipeA);
        rbTipeA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbTipeA.setText("Tipe A");
        rbTipeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTipeAActionPerformed(evt);
            }
        });

        radioButton.add(rbTipeB);
        rbTipeB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbTipeB.setText("Tipe B");
        rbTipeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTipeBActionPerformed(evt);
            }
        });

        radioButton.add(rbTipeC);
        rbTipeC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbTipeC.setText("Tipe C");
        rbTipeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTipeCActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Luas Tanah");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Luas Bangunan");

        txtPriceBuilding.setEditable(false);
        txtPriceBuilding.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtLargeLand.setEditable(false);
        txtLargeLand.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtLargeBuilding.setEditable(false);
        txtLargeBuilding.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Harga Total");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("DP");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Lama Cicilan");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("PPN(10%)");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Cicilan/bln");

        cbxAgreement.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxAgreement.setText("Setuju");
        cbxAgreement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAgreementActionPerformed(evt);
            }
        });

        txtTotalPrice.setEditable(false);
        txtTotalPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtInstalmentAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtDP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtPPN.setEditable(false);
        txtPPN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtInstalmentMonth.setEditable(false);
        txtInstalmentMonth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInstalmentMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstalmentMonthActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Bulan");

        btnProcess.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProcess.setText("PROSES");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("SIMPAN");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("BERSIH");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("/m²");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("/m²");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Harga");

        txtPrice.setEditable(false);
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPriceBuilding, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addComponent(txtPriceLand))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtOrderName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbArea, javax.swing.GroupLayout.Alignment.LEADING, 0, 140, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLargeBuilding, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(txtLargeLand))))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbTipeA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTipeB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTipeC)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProcess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(70, 70, 70)
                                .addComponent(txtPrice))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(29, 29, 29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInstalmentMonth)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtInstalmentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addComponent(cbxAgreement, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDP)
                                    .addComponent(txtTotalPrice)
                                    .addComponent(txtPPN))))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtOrderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPriceLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPriceBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbTipeA)
                            .addComponent(rbTipeB)
                            .addComponent(rbTipeC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtLargeLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtLargeBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProcess)
                            .addComponent(btnSave)
                            .addComponent(btnDelete))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtInstalmentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInstalmentMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxAgreement)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbTipeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTipeAActionPerformed
        // TODO add your handling code here:
        if(cbArea.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
            radioButton.clearSelection();
        }else{
            txtLargeLand.setText("300");
            txtLargeBuilding.setText("150");
            long landPrice = Long.parseLong(txtPriceLand.getText()),
                    landLarge = Long.parseLong(txtLargeLand.getText()),
                    buildingPrice = Long.parseLong(txtPriceBuilding.getText()),
                    buildingLarge = Long.parseLong(txtLargeBuilding.getText()),
                    Price, ppn, totalPrice;
            Price = (landPrice * landLarge) + (buildingPrice * buildingLarge);
            ppn = Price * 10 / 100;
            totalPrice = Price + ppn;
            txtPrice.setText(""+Price);
            txtPPN.setText(""+ppn);
            txtTotalPrice.setText(""+totalPrice);
            txtInstalmentAmount.setText("");
            txtDP.setText("");
            txtInstalmentMonth.setText("");
        }
    }//GEN-LAST:event_rbTipeAActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        if(txtDP.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "DP harus diisi");
        }else if(txtInstalmentAmount.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi tenor cicilan");
        }else{
            long totalPrice = Long.parseLong(txtTotalPrice.getText()),
                dp = Long.parseLong(txtDP.getText()),
                instalmentAmount = Long.parseLong(txtInstalmentAmount.getText()),
                ppn, instalmentperMonth;
            instalmentperMonth = (totalPrice - dp)/instalmentAmount;
            txtInstalmentMonth.setText(""+instalmentperMonth);
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void cbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAreaActionPerformed
        // TODO add your handling code here:
        switch(cbArea.getSelectedIndex()){
            case 0:
                txtPriceLand.setText("");
                txtPriceBuilding.setText("");
                radioButton.clearSelection();
                txtLargeLand.setText("");
                txtLargeBuilding.setText("");
                txtDP.setText("");
                txtInstalmentAmount.setText("");
                txtTotalPrice.setText("");
                txtInstalmentMonth.setText("");
                txtPPN.setText("");
                cbxAgreement.setSelected(false);
                break;
            case 1:
                txtPriceLand.setText("3500000");
                txtPriceBuilding.setText("1500000");
                radioButton.clearSelection();
                txtLargeLand.setText("");
                txtLargeBuilding.setText("");
                txtDP.setText("");
                txtInstalmentAmount.setText("");
                txtTotalPrice.setText("");
                txtInstalmentMonth.setText("");
                txtPPN.setText("");
                cbxAgreement.setSelected(false);
                break;
            case 2:
                txtPriceLand.setText("2500000");
                txtPriceBuilding.setText("1000000");
                radioButton.clearSelection();
                txtLargeLand.setText("");
                txtLargeBuilding.setText("");
                txtDP.setText("");
                txtInstalmentAmount.setText("");
                txtTotalPrice.setText("");
                txtInstalmentMonth.setText("");
                txtPPN.setText("");
                cbxAgreement.setSelected(false);
                break;
            case 3:
                txtPriceLand.setText("1500000");
                txtPriceBuilding.setText("500000");
                radioButton.clearSelection();
                txtLargeLand.setText("");
                txtLargeBuilding.setText("");
                txtDP.setText("");
                txtInstalmentAmount.setText("");
                txtTotalPrice.setText("");
                txtInstalmentMonth.setText("");
                txtPPN.setText("");
                cbxAgreement.setSelected(false);
                break;
        }
    }//GEN-LAST:event_cbAreaActionPerformed

    private void rbTipeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTipeBActionPerformed
        // TODO add your handling code here:
        if(cbArea.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
            radioButton.clearSelection();
        }else{
            txtLargeLand.setText("200");
            txtLargeBuilding.setText("100");
            long landPrice = Long.parseLong(txtPriceLand.getText()),
                    landLarge = Long.parseLong(txtLargeLand.getText()),
                    buildingPrice = Long.parseLong(txtPriceBuilding.getText()),
                    buildingLarge = Long.parseLong(txtLargeBuilding.getText()),
                    Price, ppn, totalPrice;
            Price = (landPrice * landLarge) + (buildingPrice * buildingLarge);
            ppn = Price * 10 / 100;
            totalPrice = Price + ppn;
            txtPrice.setText(""+Price);
            txtPPN.setText(""+ppn);
            txtTotalPrice.setText(""+totalPrice);
            txtInstalmentAmount.setText("");
            txtDP.setText("");
            txtInstalmentMonth.setText("");
        }
    }//GEN-LAST:event_rbTipeBActionPerformed

    private void rbTipeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTipeCActionPerformed
        // TODO add your handling code here:
        if(cbArea.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
            radioButton.clearSelection();
        }else{
            txtLargeLand.setText("100");
            txtLargeBuilding.setText("50");
            long landPrice = Long.parseLong(txtPriceLand.getText()),
                    landLarge = Long.parseLong(txtLargeLand.getText()),
                    buildingPrice = Long.parseLong(txtPriceBuilding.getText()),
                    buildingLarge = Long.parseLong(txtLargeBuilding.getText()),
                    Price, ppn, totalPrice;
            Price = (landPrice * landLarge) + (buildingPrice * buildingLarge);
            ppn = Price * 10 / 100;
            totalPrice = Price + ppn;
            txtPrice.setText(""+Price);
            txtPPN.setText(""+ppn);
            txtTotalPrice.setText(""+totalPrice);
            txtInstalmentAmount.setText("");
            txtDP.setText("");
            txtInstalmentMonth.setText("");
        }
    }//GEN-LAST:event_rbTipeCActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        txtOrderName.setText("");
        cbArea.setSelectedIndex(0);
        txtPriceLand.setText("");
        txtPriceBuilding.setText("");
        radioButton.clearSelection();
        txtLargeLand.setText("");
        txtLargeBuilding.setText("");
        txtPrice.setText("");
        txtPPN.setText("");
        txtTotalPrice.setText("");
        txtDP.setText("");
        txtInstalmentAmount.setText("");
        txtInstalmentMonth.setText("");
        cbxAgreement.setSelected(false);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cbxAgreementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAgreementActionPerformed
        // TODO add your handling code here:
        if(txtOrderName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama pemesan harus diisi");
            cbxAgreement.setSelected(false);
        }else if(txtInstalmentMonth.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tekan tombol proses terlebih dahulu");
            cbxAgreement.setSelected(false);
        }else if(cbxAgreement.isSelected()==true){
            JOptionPane.showMessageDialog(null, "Pemesan menyetujui");
            cbxAgreement.setSelected(true);
        }else{
            JOptionPane.showMessageDialog(null, "Pesanan belum disetujui");
            cbxAgreement.setSelected(false);
        }
    }//GEN-LAST:event_cbxAgreementActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(cbxAgreement.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Klik setuju untuk simpan data",
                    "Error",JOptionPane.ERROR_MESSAGE);
        }else{
            String typeHouse;
            if(rbTipeA.isSelected()){
                typeHouse = "Tipe A";
            }else if(rbTipeB.isSelected()){
                typeHouse = "Tipe B";
            }else{
                typeHouse = "Tipe C";
            }
            String largeHouse;
            if(rbTipeA.isSelected()){
                largeHouse = "300m²/150m²";
            }else if(rbTipeB.isSelected()){
                largeHouse = "200m²/100m²";
            }else{
                largeHouse = "100m²/50m²";
            }
            try{
                String sql = "INSERT INTO rumah (nama, area, tipe, luas, harga, jml_cicilan, cicilan_bln) VALUES ('"
                        + txtOrderName.getText() + "','"
                        + cbArea.getSelectedItem() + "','"
                        + typeHouse + "','"
                        + largeHouse + "','"
                        + txtTotalPrice.getText() + "','"
                        + txtInstalmentAmount.getText() + "','"
                        + txtInstalmentMonth.getText() + "')";
                Connection conn = (Connection)ConnectionDb.connectDatabase();
                PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            OptionMenu optionMenu = new OptionMenu();
            optionMenu.setVisible(true);
            this.getDesktopPane().add(optionMenu);
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtInstalmentMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstalmentMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstalmentMonthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbArea;
    private javax.swing.JCheckBox cbxAgreement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup radioButton;
    private javax.swing.JRadioButton rbTipeA;
    private javax.swing.JRadioButton rbTipeB;
    private javax.swing.JRadioButton rbTipeC;
    private javax.swing.JTextField txtDP;
    private javax.swing.JTextField txtInstalmentAmount;
    private javax.swing.JTextField txtInstalmentMonth;
    private javax.swing.JTextField txtLargeBuilding;
    private javax.swing.JTextField txtLargeLand;
    private javax.swing.JTextField txtOrderName;
    private javax.swing.JTextField txtPPN;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPriceBuilding;
    private javax.swing.JTextField txtPriceLand;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
